version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      build:
        steps:
          - checkout
          - run: yarn install
          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json"}}
          - run: yarn test
      
